# Generated by Django 4.2.1 on 2023-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-11-11'),
            preserve_default=False,
        ),
    ]
